# Generated by Django 4.1.1 on 2022-09-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id_number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
