# Generated by Django 4.1.1 on 2022-09-18 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_alter_account_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='receiver',
            field=models.ForeignKey(limit_choices_to={'role': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
