# Generated by Django 4.1.1 on 2022-09-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0003_alter_ticket_receiver'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('sender', 'title', 'receiver'), name='Ticket Constraint'),
        ),
    ]
