# Generated by Django 3.2.6 on 2022-09-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_ticket_ticket constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='Ticket Constraint',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('sender', 'receiver', 'title')},
        ),
    ]
