# Generated by Django 3.2.6 on 2022-09-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0005_auto_20220918_2356'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('receiver', 'title', 'content')},
        ),
    ]
